### ISSUE TITLE
Allow safe account login

### ISSUE THREAD

**Issue by DannyBen** [containership/containership.cli#31]
As I understand, in order to work with the CLI against my containership account, I need to run:

    $ cs cloud account login github

This means that in order to login, I need to supply my **fully-privileged** github credentials. Did I get this right? If so, this is highly unorthodox.

I expect to be able to log in without involving third party credentials, especially to such a sensitive service.

I expect it to be done by using a token (or token+secret) provided by the Containership dashboard, or at least a containership-generated user/password set. 

I would imagine that the place on the dashboard, where you provide the `cs cloud cluster ...` command should also give me a `cs cloud account login TOKEN` command.

![image](https://user-images.githubusercontent.com/2405099/29484119-b4f677ae-84c0-11e7-80df-4be555acc74c.png)

**Comment by normanjoyner** [comment]
@DannyBen currently when logging in with GitHub, a GitHub personal access token with scope `user` and `repo` is created. See https://github.com/containership/containership.plugin.cloud/blob/3ebe701b6aac62c038cd71bb92691ac3ac6d6582/lib/integrations/github.js#L60. The `repo` scope has since been removed from the OAuth signup process for Containership Cloud, so it should also be removed from the cloud plugin. I've made a ticket for that containership/containership.plugin.cloud#140. I think it makes sense to add a command that will accept Containership Cloud personal access tokens that can be created from the Containership Cloud UI under account settings. I've created a ticket for that as well containership/containership.cli#32. This way users will not have to reauth with GitHub outside of the OAuth signup process if they don't wish to.

**Comment by nicktate** [comment]
@DannyBen 
https://github.com/containership/containership.plugin.cloud/commit/8339aebe88e6ef63d0e443fa898d512bec2cb1cd has been merged into the cloud plugin and adds support for login with oauth token.  It will be released later today with the `2.x` containership client. I will update and close this issue once the new version is published to npm later today.

**Comment by nicktate** [comment]
@DannyBen CLI V2 has been officially released and includes the token support. You can see https://containership.github.io/containership.cli/docs/installation/ for instructions on installing. Let me know if you have any other questions!
